version: "3.9"
services:
  puppet:
    image: puppeteer-image
    container_name: dream_home
    environment:
      TZ: "America/New_York"
    volumes:
      - ./src/:/usr/src/app/src/
      - ./resources/:/usr/src/app/resources/
        # command: tail -F anything 
